//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QueueClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap back_button1 {
            get {
                object obj = ResourceManager.GetObject("back_button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_button2 {
            get {
                object obj = ResourceManager.GetObject("back_button2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_ev {
            get {
                object obj = ResourceManager.GetObject("background_ev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_1 {
            get {
                object obj = ResourceManager.GetObject("button_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_2 {
            get {
                object obj = ResourceManager.GetObject("button_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_active {
            get {
                object obj = ResourceManager.GetObject("button_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_m1 {
            get {
                object obj = ResourceManager.GetObject("button_m1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_m2 {
            get {
                object obj = ResourceManager.GetObject("button_m2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_normal {
            get {
                object obj = ResourceManager.GetObject("button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_read {
            get {
                object obj = ResourceManager.GetObject("button_read", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonmain1 {
            get {
                object obj = ResourceManager.GetObject("buttonmain1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonmain2 {
            get {
                object obj = ResourceManager.GetObject("buttonmain2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonok1 {
            get {
                object obj = ResourceManager.GetObject("buttonok1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonok2 {
            get {
                object obj = ResourceManager.GetObject("buttonok2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home_button_1 {
            get {
                object obj = ResourceManager.GetObject("home_button_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home_button_2 {
            get {
                object obj = ResourceManager.GetObject("home_button_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loading_0 {
            get {
                object obj = ResourceManager.GetObject("loading_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loading361 {
            get {
                object obj = ResourceManager.GetObject("loading361", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap L办事 {
            get {
                object obj = ResourceManager.GetObject("L办事", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap L招商引资_拷贝 {
            get {
                object obj = ResourceManager.GetObject("L招商引资_拷贝", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap L评价_拷贝_3 {
            get {
                object obj = ResourceManager.GetObject("L评价_拷贝_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap L返回按钮 {
            get {
                object obj = ResourceManager.GetObject("L返回按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap L领证 {
            get {
                object obj = ResourceManager.GetObject("L领证", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap L首页按钮 {
            get {
                object obj = ResourceManager.GetObject("L首页按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nubmer_button_1 {
            get {
                object obj = ResourceManager.GetObject("nubmer_button_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nubmer_button_2 {
            get {
                object obj = ResourceManager.GetObject("nubmer_button_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon queue_ico {
            get {
                object obj = ResourceManager.GetObject("queue_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上一页_button1 {
            get {
                object obj = ResourceManager.GetObject("上一页_button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 下一页 {
            get {
                object obj = ResourceManager.GetObject("下一页", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 下一页点击后 {
            get {
                object obj = ResourceManager.GetObject("下一页点击后", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 刷卡区域 {
            get {
                object obj = ResourceManager.GetObject("刷卡区域", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 办事 {
            get {
                object obj = ResourceManager.GetObject("办事", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 办事指南 {
            get {
                object obj = ResourceManager.GetObject("办事指南", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 勾选框 {
            get {
                object obj = ResourceManager.GetObject("勾选框", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 勾选框2 {
            get {
                object obj = ResourceManager.GetObject("勾选框2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 咨询 {
            get {
                object obj = ResourceManager.GetObject("咨询", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 对勾 {
            get {
                object obj = ResourceManager.GetObject("对勾", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 底部黑色 {
            get {
                object obj = ResourceManager.GetObject("底部黑色", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 弹窗新 {
            get {
                object obj = ResourceManager.GetObject("弹窗新", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 弹窗新__1_ {
            get {
                object obj = ResourceManager.GetObject("弹窗新__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 弹窗确认按钮 {
            get {
                object obj = ResourceManager.GetObject("弹窗确认按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 弹窗确认按钮2 {
            get {
                object obj = ResourceManager.GetObject("弹窗确认按钮2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 弹窗背景 {
            get {
                object obj = ResourceManager.GetObject("弹窗背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 感谢您的评价 {
            get {
                object obj = ResourceManager.GetObject("感谢您的评价", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 招商引资 {
            get {
                object obj = ResourceManager.GetObject("招商引资", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 按钮 {
            get {
                object obj = ResourceManager.GetObject("按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 按键3 {
            get {
                object obj = ResourceManager.GetObject("按键3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 按键890 {
            get {
                object obj = ResourceManager.GetObject("按键890", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 按键lol {
            get {
                object obj = ResourceManager.GetObject("按键lol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 提交_button1 {
            get {
                object obj = ResourceManager.GetObject("提交_button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 提交_button2 {
            get {
                object obj = ResourceManager.GetObject("提交_button2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 提示框1 {
            get {
                object obj = ResourceManager.GetObject("提示框1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 提示框2 {
            get {
                object obj = ResourceManager.GetObject("提示框2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 提示框新 {
            get {
                object obj = ResourceManager.GetObject("提示框新", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 数字按钮 {
            get {
                object obj = ResourceManager.GetObject("数字按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 数字按钮2 {
            get {
                object obj = ResourceManager.GetObject("数字按钮2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 数字按键 {
            get {
                object obj = ResourceManager.GetObject("数字按键", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 数字新 {
            get {
                object obj = ResourceManager.GetObject("数字新", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 未选中 {
            get {
                object obj = ResourceManager.GetObject("未选中", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 条框 {
            get {
                object obj = ResourceManager.GetObject("条框", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 满意灰色按钮 {
            get {
                object obj = ResourceManager.GetObject("满意灰色按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 满意蓝色按钮 {
            get {
                object obj = ResourceManager.GetObject("满意蓝色按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 矩形 {
            get {
                object obj = ResourceManager.GetObject("矩形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 确认_button1 {
            get {
                object obj = ResourceManager.GetObject("确认_button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 确认_button2 {
            get {
                object obj = ResourceManager.GetObject("确认_button2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 确认按钮 {
            get {
                object obj = ResourceManager.GetObject("确认按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 确认按钮2 {
            get {
                object obj = ResourceManager.GetObject("确认按钮2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 背景 {
            get {
                object obj = ResourceManager.GetObject("背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 蓝色_点击前1 {
            get {
                object obj = ResourceManager.GetObject("蓝色_点击前1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 评价 {
            get {
                object obj = ResourceManager.GetObject("评价", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 评价界面效果图 {
            get {
                object obj = ResourceManager.GetObject("评价界面效果图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 评价背景 {
            get {
                object obj = ResourceManager.GetObject("评价背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 请输入身份证号码 {
            get {
                object obj = ResourceManager.GetObject("请输入身份证号码", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 请选择您要办理的类型 {
            get {
                object obj = ResourceManager.GetObject("请选择您要办理的类型", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 边框123 {
            get {
                object obj = ResourceManager.GetObject("边框123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 返回按钮 {
            get {
                object obj = ResourceManager.GetObject("返回按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 返回按钮2 {
            get {
                object obj = ResourceManager.GetObject("返回按钮2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 部门下一页 {
            get {
                object obj = ResourceManager.GetObject("部门下一页", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 部门下一页_蓝色 {
            get {
                object obj = ResourceManager.GetObject("部门下一页_蓝色", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 部门点击后_灰色方框 {
            get {
                object obj = ResourceManager.GetObject("部门点击后_灰色方框", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 部门蓝色背景_拷贝_11 {
            get {
                object obj = ResourceManager.GetObject("部门蓝色背景_拷贝_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 银色_点击后1 {
            get {
                object obj = ResourceManager.GetObject("银色_点击后1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 预约下一页 {
            get {
                object obj = ResourceManager.GetObject("预约下一页", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 预约下一页点击后 {
            get {
                object obj = ResourceManager.GetObject("预约下一页点击后", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 预约勾选框 {
            get {
                object obj = ResourceManager.GetObject("预约勾选框", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 预约勾选框1 {
            get {
                object obj = ResourceManager.GetObject("预约勾选框1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 预约提交 {
            get {
                object obj = ResourceManager.GetObject("预约提交", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 预约提交_蓝色按钮 {
            get {
                object obj = ResourceManager.GetObject("预约提交_蓝色按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 预约未选中 {
            get {
                object obj = ResourceManager.GetObject("预约未选中", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 预约背景 {
            get {
                object obj = ResourceManager.GetObject("预约背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 预约选中 {
            get {
                object obj = ResourceManager.GetObject("预约选中", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 领证 {
            get {
                object obj = ResourceManager.GetObject("领证", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 首页按钮 {
            get {
                object obj = ResourceManager.GetObject("首页按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 首页按钮2 {
            get {
                object obj = ResourceManager.GetObject("首页按钮2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
